version: "3.7"
services:
  register:
    image: register:latest
    ports:
      - 8761:8761    
    depends_on:
      - config
      - zipkin
  config:
    image: config:latest
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    ports:
      - 8888:8888
  proxy:
    image: proxy:latest
    environment:
      - JAVA_OPTS=
        - DEUREKA_SERVER=http://discovery:8761/eureka

    restart: on-failure
    depends_on:
      - register
      - config
      - zipkin
      - mysql_db
    ports:
      - 8088:8088
    command: sh -c './wait-for mysql_db:3306 -- npm start'

#  Hr:
#    image: hr:latest
#    environment:
#        - JAVA_OPTS=
#         - DEUREKA_SERVER=http://discovery:8761/eureka
#    depends_on:
#      - register
#      - config
#      - zipkin
#    ports:
#      - 7070:7070
  zipkin:
    image: zipkin:latest
    depends_on:
      - config
    ports:
      - 9411:9411

  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: proxy
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root